name: portfolio-jim
recipe: drupal10
config:
  php: '8.2'
  webroot: docroot
  database: mysql:5.7

services:
  appserver:
    xdebug: true
    build_as_root:
      - apt-get update -y && apt-get install -y git unzip
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  database:
    portforward: true

tooling:
  drush:
    service: appserver
    cmd: "vendor/bin/drush"
  php:
    service: appserver
  composer:
    service: appserver
    cmd: "composer"

proxy:
  appserver:
    - portfolio.lndo.site