name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2024-09-05
version: '10.3.3'
project: 'drupal'
datestamp: 1725528273
