name: 'Configuration Manager'
type: module
description: 'Allows importing and exporting configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2024-09-05
version: '10.3.3'
project: 'drupal'
datestamp: 1725528273
